version: '3.8'
name: architecture
services:
  redis_assignment:
    image: redis:latest
    container_name: redis_assignment
    hostname: redis
    volumes:
      - /var/lib/redis
    ports:
      - '6377:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HOST=${REDIS_HOST}
    env_file:
      - .env
  postgres_assignment:
    image: postgres:12-alpine
    container_name: postgres_assignment
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kientruc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  postgres_data:
